max_depth:
  low: 3
  high: 12
  method: int
learning_rate:
  low: 0.01
  high: 0.3
  method: float
n_estimators:
  low: 100
  high: 2000
  method: int
subsample:
  low: 0.5
  high: 1.0
  method: float
colsample_bytree:
  low: 0.5
  high: 1.0
  method: float
gamma:
  low: 0
  high: 5
  method: float
min_child_weight:
  low: 1
  high: 10
  method: int
reg_alpha:
  low: 0
  high: 1
  method: float
reg_lambda:
  low: 0
  high: 1
  method: float
